#!/bin/bash

DEST=/etc/unbound/unbound.conf.d/adnix.conf

DIR=$(dirname "$0")
[[ -e "$DEST" ]] && OLD=$(md5sum "$DEST" | cut -f 1 -d ' ')
if $DIR/adnix --address 0.0.0.0 --v6address :: --file "$DEST" "$@"; then
	[[ -e "$DEST" ]] && NEW=$(md5sum "$DEST" | cut -f 1 -d ' ')
	if [[ "$OLD" != "$NEW" ]]; then
		echo "INFO: Hosts list has been updated"
		systemctl reload unbound
	else
		echo "INFO: Hosts list is already up to date"
	fi
else
	echo "ERROR: adnix failed!"
fi
